seed: 1
model: 'SPACE'
exp_name: pong
resume: false
load_time_consistency: true
add_flow: true

resume_ckpt: '../pretrained/atari_joint.pth'
# '../output/checkpoints/mspacman_atari_pretrained/model.pth'
#
# '../output/checkpoints/mspacman_atari+z_what_1e-2/model_000162501.pth'
#'../output/checkpoints/mspacman_atari+z_area_object_1e1/model_000186501.pth'
# '../output/checkpoints/mspacman_baseline/model_000177001.pth'
# 'result_checkpoints/base_z_what_model_000078001.pth'
# 'output/checkpoints/atari_mspacman/model_000079001.pth'
# '../pretrained/atari_joint.pth'
parallel: true
device_ids: [4, 5, 6, 7]
device: 'cuda:4'

logdir: '../output/logs/mode'
checkpointdir: '../output/checkpoints/mode'
evaldir: '../output/eval'

dataset: 'ATARI'
dataset_roots:
  OBJ3D_SMALL: '../data/OBJ3D_SMALL'
  OBJ3D_LARGE: '../data/OBJ3D_LARGE'
  ATARI: '../aiml_atari_data2/space_like'


train:
  batch_size: 16
  max_epochs: 1000
  max_steps: 20000
  print_every: 200
  save_every: 500
  num_workers: 4
  clip_norm: 1.0
  max_ckpt: 4
  eval_on: true
  eval_every: 200
  solver:
    fg:
      optim: 'RMSprop'
      lr: 5e-5
    bg:
      optim: 'Adam'
      lr: 1e-3

arch:
  motion_input: false
  motion: true
  motion_kind: 'mode'
  G: 16
  fg_sigma: 0.20

  z_pres_start_step: 0
  z_pres_end_step: 8000
  z_pres_start_value: 0.1
  z_pres_end_value: 1e-10

  z_scale_mean_start_step: 0
  z_scale_mean_end_step: 20000
  z_scale_mean_start_value: -2.0
  z_scale_mean_end_value: -2.5

  tau_start_step: 0
  tau_end_step: 10000
  tau_start_value: 2.5
  tau_end_value: 2.5

  fix_alpha_steps: -1
  fix_alpha_value: 0.1

  K: 2
  bg_sigma: 0.10
  boundary_loss: false

gamelist: [
    'Pong-v0',
    ]

